const API = "";
let token = "";
let products = [];
const $ = (id) => document.getElementById(id);
async function request(path, options={}) { const headers={"Content-Type":"application/json",...(options.headers||{})}; if(token) headers.Authorization=`Bearer ${token}`; const r=await fetch(`${API}/api/admin${path}`,{...options,headers}); const data=await r.json().catch(()=>({message:"Invalid response"})); if(!r.ok) throw new Error(data.message||"Request failed"); return data; }
function reset(){["pid","name","category","price","stock","image","blurb"].forEach(id=>$(id).value=""); $("formTitle").textContent="Add product";}
function render(){const q=$("filter").value.toLowerCase(); $("products").innerHTML=products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(q)).map(p=>`<article class="product">${p.image?`<img src="${p.image}" alt="">`:''}<strong>${esc(p.name)}</strong><div>${esc(p.category)}</div><div>KES ${p.price==null?'—':Number(p.price).toLocaleString()}</div><div class="stock">Stock: ${p.stock==null?'Not set':p.stock}</div><p>${esc(p.blurb||'')}</p><div class="row"><button onclick="editProduct('${p.id}')">Edit</button><button class="danger" onclick="removeProduct('${p.id}')">Remove</button></div></article>`).join("")||'<p class="muted">No products found.</p>';}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
window.editProduct=(id)=>{const p=products.find(x=>x.id===id); if(!p)return; ["pid","name","category","price","stock","image","blurb"].forEach(k=>$(k).value=p[k]??""); $("formTitle").textContent=`Edit: ${p.name}`; window.scrollTo({top:0,behavior:'smooth'});};
window.removeProduct=async(id)=>{if(!confirm('Remove this product from the live catalogue?'))return; try{await request(`/products/${encodeURIComponent(id)}`,{method:'DELETE'});await load();}catch(e){alert(e.message)}};
async function load(){const data=await request('/products');products=data.products;render();}
$("loginBtn").onclick=async()=>{try{const r=await request('/login',{method:'POST',body:JSON.stringify({password:$("password").value})}); token=r.token; $("login").classList.add('hidden'); $("dashboard").classList.remove('hidden'); await load();}catch(e){$("loginStatus").textContent=e.message}};
$("saveBtn").onclick=async()=>{try{const id=$("pid").value.trim()||undefined; const payload={id,name:$("name").value.trim(),category:$("category").value.trim(),price:$("price").value===''?null:Number($("price").value),stock:$("stock").value===''?null:Number($("stock").value),image:$("image").value.trim(),blurb:$("blurb").value.trim()}; if(!payload.name||!payload.category)throw new Error('Name and category are required.'); await request(id?`/products/${encodeURIComponent(id)}`:'/products',{method:id?'PUT':'POST',body:JSON.stringify(payload)}); $("formStatus").textContent='Saved.'; reset(); await load();}catch(e){$("formStatus").textContent=e.message}};
$("cancelBtn").onclick=reset; $("refreshBtn").onclick=load; $("filter").oninput=render;